# fly.toml app configuration
app = "guestbook-api"
primary_region = "sjc"

[build]
  builder = "heroku"
  buildpacks = ["heroku/buildpacks:20"]

[build.args]
  BUN_VERSION = "latest"

[env]
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
