services:
  - type: web
    name: guestbook-api
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    dockerfilePath: ./Dockerfile
    ports:
      - port: 3000
        protocol: HTTP
