sonar.projectKey=tgr-wjya_guestbook-api
sonar.organization=tgr-wjya-1

# Coverage
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# Only analyze source files
sonar.sources=src
sonar.tests=tests

# Exclusions
sonar.exclusions=node_modules/**,coverage/**,index.ts,index2.ts,index2.test.ts,index.test.ts
sonar.test.exclusions=tests/**
sonar.coverage.exclusions=tests/**
